repos:
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.6
  hooks:
  - id: bandit
    exclude: tests/
    skips: ["B608",]

- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    exclude: migrations/

- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    args: ["--preview","--config","pyproject.toml"]
    # language_version: python3.11.12

- repo: https://github.com/PyCQA/isort
  rev: 6.0.1
  hooks:
  - id: isort
    exclude: build-run-commands/
    args: ["--profile=black", --line-length=79]